### PR TITLE
Update lerna, husky, eslint & lint-staged

### PR DESCRIPTION
**Pull request by clement26695**

### CODE REVIEW

**Comment by bd82** [comment]
Try enabling greenkeeper or dependentBot and it will help keep the depedencies up-to-date in a more automated manner. 

e.g: https://github.com/SAP/chevrotain/pull/971

**Comment by bd82** [comment]
I see dependent-bot is already enabled on this repo.
Why do we need manual deps updates in this case?

**Comment by clement26695** [comment]
I'm not sure why, but it doesn't update package.json, but only the yarn.lock file

**Comment by bd82** [comment]
> I'm not sure why, but it doesn't update package.json, but only the yarn.lock file

Wierd maybe it only supports updating according to version ranges...

**Pull request merged**
