### PR TITLE
Improve unicode generation

### PR DESCRIPTION
**Pull request by Shaolans**
This is an improvement of unicode generation from #169.
A short comment is added on the generated unicode file.
The size of the file is going from 2+mb down to ~200kb by reusing firstCharset and generating loop to write ranges.

### CODE REVIEW

**Comment by Shaolans** [comment]
I extended the loop optimization, it is down to ~25kb now.

**Comment by bd82** [comment]
This looks good 👍 

I will merge this:
A couple of small upgrades that can be done separately:
- Give meaningful names to variables and functions (we have a function called "f" here for some reason...).
- It's OK to generate a comment or there if it helps in understanding the file (imagine looking at it 6 months down the road when you don't have any context).
- What is the execution time of this large file compared to the previous one? do the loops increase it too much? if it is just a few mili-seconds it does not matter...

**Comment by pascalgrimaud** [comment]
good job @Shaolans

**Comment by Shaolans** [comment]
> Give meaningful names to variables and functions (we have a function called "f" here for some reason...).
> It's OK to generate a comment or there if it helps in understanding the file (imagine looking at it 6 months down the road when you don't have any context).

I called it "f", to gain some spaces but since I have refactored it to reduce the number of call, I will change the name.
For the comment, I was trying to save some space but know since we have a correct size file, I fill make a clear comment on it.

> What is the execution time of this large file compared to the previous one? do the loops increase it too much? if it is just a few mili-seconds it does not matter...

```
Unicode benchmark
Unicode without loop x 8.32 ops/sec ±1.33% (25 runs sampled)
Unicode with loops x 9.83 ops/sec ±0.88% (28 runs sampled)
Fastest is Unicode with loops
```
I made a little benchmark and it seems that the loops peforms event better !
Using loops seems to work better than loading a large size file :smile: 

> good job @Shaolans 
Thanks ! :laughing:

**Comment by bd82** [comment]
> I called it "f", to gain some spaces but since I have refactored it to reduce the number of call, I will change the name.

Treat the generated code as regular code. The intent is not to reduce every single bit of space/memory.
Rather to make clear code that is easy to understand and that is in reasonable size.
If somebody needs to reduce the code size significantly they would use a code minifier (e.g uglifyJS).

> Unicode benchmark
Unicode without loop x 8.32 ops/sec ±1.33% (25 runs sampled)
Unicode with loops x 9.83 ops/sec ±0.88% (28 runs sampled)
Fastest is Unicode with loops

What is this benchmark? Parsing time or loading time for the unicode.js file?

**Comment by Shaolans** [comment]
> What is this benchmark? Parsing time or loading time for the unicode.js file?
This is the benchmark of the loading time for unicodesets.js, the generated file.


The following one is benchmarking the time taken by unicode.js to generate unicodesets.js
```
Unicode benchmarking runtime unicode.js
Unicode without loop x 4.67 ops/sec ±0.89% (16 runs sampled)
Unicode with loops x 8.83 ops/sec ±0.73% (26 runs sampled)
Fastest is Unicode with loops
````

**Comment by bd82** [comment]
> This is the benchmark of the loading time for unicodesets.js, the generated file.

Ohh, so 100ms to load that file? ouch

**Comment by Shaolans** [comment]
> Ohh, so 100ms to load that file? ouch

It should be noted that I was using a pretty old computer and since I only wanted to see the difference I launch node command on unicodesets.js. It is probably better to just call require and clear the require cache at each run.

**Comment by bd82** [comment]
I have a pretty modern computer and it was 50ms, after the upgrade to imperative logic
it is 30ms+ which is still a bit slow but not horrible... 😄

**Pull request merged**
