### PR TITLE
Feature/formater on off

### LINKED ISSUE #287: Handle @formatter:off and @formatter:on ?
`// @formatter:off` and `// @formatter:on` are commonly used and recognized by Eclipse and IntelliJ.
I wonder if prettier-java should handle them too, a bit like `// prettier-ignore`

### PR DESCRIPTION
**Pull request by clementdessoude**
Hi @nonomoho!

I tried to fix the conflicts between your branch and master. Can you have a look and tell me if you think it is ok?

Fix #287

### CODE REVIEW

**Comment by nonomoho** [comment]
LGTM! Thanks for the help on it :blush:

**Comment by nonomoho** [comment]
Half bounty claimed: https://opencollective.com/generator-jhipster/expenses/12288

**Comment by pascalgrimaud** [comment]
approuved @nonomoho
Don't forget yours @clementdessoude

**Comment by clementdessoude** [comment]
Bounty claimed too 😃! https://opencollective.com/generator-jhipster/expenses/12622

**Comment by pascalgrimaud** [comment]
just approuved @clementdessoude

**Pull request merged**
